/*
 * main.c - Auto-generated by Anjuta's Makefile project wizard
 *
 */


    /* Standard-Libraries */
#include <stdbool.h>
#include <inttypes.h>
#include <unistd.h>

    /* Bibliotheken */
#include <libusb-1.0/libusb.h>
#include <popt.h>                       /* Parsen von Kommandozeilen-Optionen */

#include "global.h"
#include "softrock.h"

struct libusb_context *usb_context;
struct libusb_device_handle *fifisdr;


/* Variablen für Argumente aus der Kommandozeile */
int cmdline_write = false;
long cmdline_vid = 0x16C0;
long cmdline_pid = 0x05DC;
int cmdline_abpf = false;
long cmdline_index = -1;
double cmdline_freq = -999.0;
int cmdline_vco = false;
int cmdline_xtal = false;
int cmdline_3rd = false;
int cmdline_5th = false;
int cmdline_presel = false;
int cmdline_i2c = false;
long cmdline_pattern = -1;
long cmdline_mode = -1;
double cmdline_freq_from = -999.0;
double cmdline_freq_to = -999.0;
/*
char *cmdline_outdir = "";
*/



/* USB-Fehler in Klartext */
void print_usb_error (int error)
{
    switch (error) {
    case LIBUSB_ERROR_ACCESS:
        printf ("libusb: Keine Zugriffsrechte\n");
    break;
    case LIBUSB_ERROR_NO_DEVICE:
        printf ("libusb: Jemand war schneller (FiFi-SDR wieder abgesteckt)\n");
    break;
    case LIBUSB_ERROR_TIMEOUT:
        printf ("libusb: Timeout\n");
    break;
    case LIBUSB_ERROR_NO_MEM:
        printf ("libusb: Kein Speicher\n");
    break;

    default: printf ("Unbekannter USB-Fehler (%d)\n", error); break;
    };
}


/* FiFi-SDR suchen und öffnen */
bool such_fifi (void)
{
    struct libusb_device **devices;                 /* Geräteliste */
    ssize_t cnt;                                    /* Anzahl Geräte */
    ssize_t n;
    struct libusb_device *device;
    struct libusb_device_descriptor desc_device;
    int error;
    bool found;


    /* Info über alle angeschlossenen Geräte holen */
    cnt = libusb_get_device_list (usb_context, &devices);
    if (cnt <= 1)
    {
        printf ("Kein USB-Gerät an diesem PC angeschlossen\n");
        return false;
    }

    /* Ist ein passendes Gerät dabei? */
    found = false;
    for (n = 0; n < cnt; n++)
    {
        /* Geräteinfo holen */
        device = devices[n];

        /* Prüfen ob dies das passende Gerät ist */
        error = libusb_get_device_descriptor (device, &desc_device);
        if (error != 0)
        {
            printf ("Kann Device Descriptor nicht lesen\n");
            break;
        }
        if ((cmdline_vid == desc_device.idVendor) &&
            (cmdline_pid == desc_device.idProduct))
        {
            found = true;
            break;
        }
    }

    /* Kann es los gehen? */
    if (found)
    {
        error = libusb_open (device, &fifisdr);
        if (error != 0)
        {
            print_usb_error (error);
            found = false;
        }
    }

    libusb_free_device_list (devices, 1);

    return found;
}




#include <stdio.h>
int main (int argc, char *argv[])
{
    bool ok;
    int i;


    /* Kommandozeilen-Parameter */
    struct poptOption optionsTable[] =
    {
        { "write", 'w', POPT_ARG_NONE, &cmdline_write, 0,
                "Werte schreiben" },
        { "vid", '\0', POPT_ARG_LONG, &cmdline_vid, 0,
                "USB-PID des FiFi-SDR (Vorgabe: 0x16C0)" },
        { "pid", '\0', POPT_ARG_LONG, &cmdline_pid, 0,
                "USB-VID des FiFi-SDR (Vorgabe: 0x05DC)" },
        { "abpf", '\0', POPT_ARG_NONE, &cmdline_abpf, 0,
                "Zugriff auf automatisches Bandpaßfilter" },
        { "index", '\0', POPT_ARG_LONG, &cmdline_index, 0,
                "Index für z.B. ABPF" },
        { "freq", '\0', POPT_ARG_DOUBLE, &cmdline_freq, 0,
                "Frequenzangabe [MHz]" },
        { "vco", '\0', POPT_ARG_NONE, &cmdline_vco, 0,
                "VCO-Frequenz" },
        { "xtal", '\0', POPT_ARG_NONE, &cmdline_xtal, 0,
                "Quarz-Frequenz" },
        { "3rd", '\0', POPT_ARG_NONE, &cmdline_3rd, 0,
                "Start für RX auf 3. Oberwelle" },
        { "5th", '\0', POPT_ARG_NONE, &cmdline_5th, 0,
                "Start für RX auf 5. Oberwelle" },
        { "presel", '\0', POPT_ARG_NONE, &cmdline_presel, 0,
                "Preselektor" },
        { "pattern", '\0', POPT_ARG_LONG, &cmdline_pattern, 0,
                "Pattern für z.B. Preselektor" },
        { "mode", '\0', POPT_ARG_LONG, &cmdline_mode, 0,
                "Modus für Preselektor" },
        { "freq-from", '\0', POPT_ARG_DOUBLE, &cmdline_freq_from, 0,
                "Startfrequenz [MHz]" },
        { "freq-to", '\0', POPT_ARG_DOUBLE, &cmdline_freq_to, 0,
                "Endfrequenz [MHz]" },
        { "i2c", '\0', POPT_ARG_NONE, &cmdline_i2c, 0,
                "I2C-Adresse lesen" },
#if 0
        { "outdir", 'o', POPT_ARG_STRING, &cmdline_outdir, 0,
                "Verzeichnis für die Ausgabe der Karten" },
#endif
        POPT_AUTOHELP
        { NULL, POPT_ARG_NONE, 0, NULL, 0 }
    };

    /* Kommandozeile parsen */
    poptContext optCon;
    optCon = poptGetContext (NULL, argc, (const char **)argv, optionsTable, 0);
    poptSetOtherOptionHelp( optCon, " [options]" );

    /* Kurz-Hilfe, wenn gar keine Argumente angegeben werden. */
    if (argc < 2)
    {
        poptPrintUsage( optCon, stderr, 0 );
        return 1;
    }

    /* Optionskürzel abfragen */
    char c;
    while ((c = poptGetNextOpt(optCon)) >= 0)
    {
	}

    /* Prüfen, ob ein Fehler bei der Bearbeitung der Optionen aufgetreten ist. */
    if( c < -1 )
    {
        printf ("\"%s\" %s\n", poptBadOption( optCon, POPT_BADOPTION_NOALIAS ), poptStrerror(c) );
        return 1;
    }

    poptFreeContext( optCon );

    /* libusb initialisieren */
    if (libusb_init (&usb_context) != 0)
    {
        printf ("libusb_init ging daneben :-(\n");
        return 1;
    }

    /* FiFi-SDR suchen und öffnen */
    if (such_fifi())
    {
        ok = true;

        /* ABPF? */
        if (cmdline_abpf)
        {
            /* Beim Schreiben Werte prüfen */
            if (cmdline_write)
            {
                if ((cmdline_index < 0) || (cmdline_freq < 0.0))
                {
                    ok = false;
                }
            }
            else
            {
                /* Index und Frequenz haben feste Werte */
                cmdline_index = 255;
                cmdline_freq = 0.0;
            }

            if (ok)
            {
                if (softrock_get_set_abpf (fifisdr, cmdline_index, _11_5(4.0 * cmdline_freq)))
                {
                    /* Aktuelle Werte zeigen */
                    softrock_show_abpf();
                }
            }
        }

        /* VCO-Frequenz */
        if (cmdline_vco)
        {
            /* Beim Schreiben Werte prüfen */
            if (cmdline_write)
            {
                if (cmdline_freq < 0.0)
                {
                    printf ("Keine Frequenz angegeben\n");
                }
                else
                {
                    softrock_write_vco (fifisdr, cmdline_freq);
                }
            }
            else
            {
                double f;
                if (softrock_read_vco (fifisdr, &f))
                {
                    printf ("VCO = %lf MHz\n", f);
                }
            }
        }

        /* Quarz-Frequenz */
        if (cmdline_xtal)
        {
            /* Beim Schreiben Werte prüfen */
            if (cmdline_write)
            {
                if (cmdline_freq < 0.0)
                {
                    printf ("Keine Frequenz angegeben\n");
                }
                else
                {
                    softrock_write_xtal (fifisdr, cmdline_freq);
                }
            }
            else
            {
                double f;
                if (softrock_read_xtal (fifisdr, &f))
                {
                    printf ("XTAL = %lf MHz\n", f);
                }
            }
        }


        /* Start-Frequenz 3. Oberwelle */
        if (cmdline_3rd)
        {
            /* Beim Schreiben Werte prüfen */
            if (cmdline_write)
            {
                if (cmdline_freq < 0.0)
                {
                    printf ("Keine Frequenz angegeben\n");
                }
                else
                {
                    softrock_write_3rd (fifisdr, cmdline_freq);
                }
            }
            else
            {
                double f;
                if (softrock_read_3rd (fifisdr, &f))
                {
                    printf ("3. Oberwelle ab = %lf MHz\n", f);
                }
            }
        }

        /* Start-Frequenz 5. Oberwelle */
        if (cmdline_5th)
        {
            /* Beim Schreiben Werte prüfen */
            if (cmdline_write)
            {
                if (cmdline_freq < 0.0)
                {
                    printf ("Keine Frequenz angegeben\n");
                }
                else
                {
                    softrock_write_5th (fifisdr, cmdline_freq);
                }
            }
            else
            {
                double f;
                if (softrock_read_5th (fifisdr, &f))
                {
                    printf ("5. Oberwelle ab = %lf MHz\n", f);
                }
            }
        }

        /* Preselektor */
        if (cmdline_presel)
        {
            /* Beim Schreiben Werte prüfen */
            if (cmdline_write)
            {
                if (cmdline_mode != -1)
                {
                    if ((cmdline_mode >= 0) && (cmdline_mode <= 3))
                    {
                        softrock_write_presel_mode (fifisdr, cmdline_mode);
                    }
                    else
                    {
                        printf ("--mode nicht in [0,3]\n");
                    }
                }
                else
                {
                    if ((cmdline_index == -1) ||
                        (cmdline_freq_from < 0.0) ||
                        (cmdline_freq_to < 0.0) ||
                        (cmdline_pattern == -1))
                    {
                        printf ("--freq-from/--freq-to/--pattern prüfen\n");
                    }
                    else
                    {
                        softrock_write_presel_entry (fifisdr,
                                                     cmdline_index,
                                                     cmdline_freq_from,
                                                     cmdline_freq_to,
                                                     cmdline_pattern);
                    }
                }
            }
            else
            {
                uint32_t presel_mode;
                if (softrock_read_presel_mode (fifisdr, &presel_mode))
                {
                    printf ("Preselektor-Modus = %d%s\n",
                            presel_mode,
                            (presel_mode == 0) ? " (Es gelten die Umschaltpunkte für ABPF)" : "");
                }

                uint32_t pattern;
                double f1, f2;
                for (i = 0; i < 16; i++)
                {
                    if (softrock_read_presel_entry (fifisdr, i, &f1, &f2, &pattern))
                    {
                        printf ("%2d: %10lf - %10lf MHz, Ausgänge = %c%c%c%cb (%d)\n",
                                      i, f1, f2,
                                      pattern & 1 ? '1' : '0',
                                      pattern & 2 ? '1' : '0',
                                      pattern & 4 ? '1' : '0',
                                      pattern & 8 ? '1' : '0',
                                      pattern & 0x0F
                                      );
                    }
                }
            }
        }

        /* I2C-Adresse */
        if (cmdline_i2c)
        {
            /* Schreiben nicht unterstützt */
            if (cmdline_write)
            {
                printf ("Schreiben der I2C-Adresse nicht möglich (wird automatisch bestimmt).\n");
            }
            else
            {
                uint8_t addr;
                if (softrock_read_i2c (fifisdr, &addr))
                {
                    printf ("I2C-Adresse = 0x%02X\n", (int)addr);
                }
            }
        }

        libusb_close (fifisdr);
    }
    else
    {
        printf ("Kein passendes FiFi-SDR gefunden\n" );
    }

    /* Nach dem Schreiben etwas warten, damit das FiFi-SDR Zeit hat das Flash zu beschreiben. */
    if (cmdline_write)
    {
        usleep (200000);    /* 200 ms */
    }

    libusb_exit (usb_context);

    return (0);
}
